# Generated by Django 4.2.2 on 2023-06-21 11:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2023, 6, 21, 11, 3, 20, 826620, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
