# Generated by Django 4.2.2 on 2023-06-21 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 6, 21, 11, 3, 43, 144669, tzinfo=datetime.timezone.utc)),
        ),
    ]
