# Generated by Django 4.2.2 on 2023-06-26 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 4, 13, 37, 676793, tzinfo=datetime.timezone.utc)),
        ),
    ]
