# Generated by Django 4.2.2 on 2023-06-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='owner',
            new_name='onwer',
        ),
    ]
