# Generated by Django 4.2.2 on 2023-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_remove_transaction_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
