# Generated by Django 4.2.2 on 2023-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_transaction_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('sell', 'Sell'), ('buy', 'Buy')], default=None, max_length=20),
        ),
    ]
